
PAYMENT_PAY_AT_DELIVERY = 0
PAYMENT_PAY_WITH_PAY = 1
PAYMENT_PAY_TOKEN = None
PAYMENT_PAY_USER = None
PAYMENT_PAY_HOST = 'http://pay-atalaku.com/api/payment-request'
PAYMENT_PAY_URL = f'{PAYMENT_PAY_HOST}/{PAYMENT_PAY_USER}/{PAYMENT_PAY_TOKEN}/'
