
ADDRESS_FOR_BILLING = 0
ADDRESS_FOR_SHIPPING = 1
ADDRESS_FOR_BILLING_AND_SHIPPING = 2

ADDRESS_TYPES = (
    (ADDRESS_FOR_BILLING, "USE THIS ADDRESS FOR BILLING"),
    (ADDRESS_FOR_SHIPPING, "USE THIS ADDRESS FOR SHIPPING"),
    (ADDRESS_FOR_BILLING_AND_SHIPPING, "USE THIS ADDRESS FOR BILLING AND SHIPPING"),
)