
GENDER_MEN          = 1
GENDER_WOMEN        = 2
GENDER_BABY_GIRL    = 3
GENDER_BABY_BOY     = 4
GENDER_GIRL         = 5
GENDER_BOY          = 6
GENDER_NO_GENDER    = 7

GENDER = (
        (GENDER_MEN, 'MEN'),
        (GENDER_WOMEN, 'WOMEN'),
        (GENDER_BABY_GIRL, 'BABY GRILD'),
        (GENDER_BABY_BOY, 'BABY BOY'),
        (GENDER_GIRL, 'GIRL'),
        (GENDER_BOY, 'BOY'),
        (GENDER_NO_GENDER, 'NO GENDER')
    )

ATTRIBUTE_TYPE_STRING = 1
ATTRIBUTE_TYPE_INTEGER = 2
ATTRIBUTE_TYPE_DECIMAL = 3
ATTRIBUTE_TYPE_DATE   = 4
ATTRIBUTE_TYPE_DATETIME = 5
ATTRIBUTE_TYPE_DEFAULT = ATTRIBUTE_TYPE_STRING

ATTRIBUTE_TYPE = (
        (ATTRIBUTE_TYPE_STRING, 'STRING'),
        (ATTRIBUTE_TYPE_INTEGER, 'INTEGER'),
        (ATTRIBUTE_TYPE_DECIMAL, 'DECIMAL'),
        (ATTRIBUTE_TYPE_DATE, 'DATE'),
        (ATTRIBUTE_TYPE_DATETIME, 'DATETIME'),
        (ATTRIBUTE_TYPE_DEFAULT, 'DEFAULT(STRING)')
    )

COMMISSION_DEFAULT = 0.03
COMMISSION_MAX_DIGITS = 7
COMMISSION_DECIMAL_PLACES = 5