WAITING = 0
PICKED_UP = 1
SHIPPED = 2
DELIVERED = 3
PROCESSING = 4
RETOURE = 5
CUSTOMER_NOT_FOUND = 6
CUSTOMER_HAS_NOT_PAID = 7
CLOSED = 8

SHIPMENT_STATUS = (
    ('WAITING', WAITING),
    ('PICKED UP', PICKED_UP),
    ('SHIPPED', SHIPPED),
    ('DELIVERED', DELIVERED),
    ('PROCESSING', PROCESSING),
    ('RETOURE', RETOURE),
    ('CUSTOMER NOT FOUND', CUSTOMER_NOT_FOUND),
    ('CUSTOMER CAN NOT PAY', CUSTOMER_HAS_NOT_PAID),
    ('CLOSED', CLOSED),
)