PAGINATED_BY = 100
PK_ULR_KWARG= 'product_uuid'

PRODUCT_LIST_CONTEXT_NAME = 'product_list'
PRODUCT_LIST_TEMPLATE_NAME = 'catalog/product_list.html'
PRODUCT_DETAIL_CONTEXT_NAME = 'product'
PRODUCT_DETAIL_TEMPLATE_NAME = 'catalog/product_detail.html'
CATALOG_HOME_TEMPLATE_NAME   = 'catalog/catalog_home.html'

LATEST_QUERYSET_LIMIT = 10

PRODUCT_PRICE_DECIMAL_PLACES = 2
PRODUCT_PRICE_MAX_DIGITS = 10
PRODUCT_NUMBER_LENGTH = 6

COMMISSION_DEFAULT = 0.03
COMMISSION_MAX_DIGITS = 7
COMMISSION_DECIMAL_PLACES = 5

CART_ITEM_RELATED_NAME = 'items'
AJAX_CONTENT_TYPE = "application/json"
