from lyshop import settings
VENDOR_GROUP = "Seller"
FEE_GROUP = "Fee"

SOLD_PRODUCT_SENT = 0
SOLD_PRODUCT_RECEIVED = 1
SOLD_PRODUCT_NOT_SENT = 2
SOLD_PRODUCT_RETURNED = 3
SOLD_PRODUCT_DELIVERED = 4

SOLD_PRODUCT_STATUS = (
    (SOLD_PRODUCT_SENT, 'PRODUCT SENT'),
    (SOLD_PRODUCT_RECEIVED, 'PRODUCT RECEIVED'),
    (SOLD_PRODUCT_NOT_SENT, 'PRODUCT NOT SENT'),
    (SOLD_PRODUCT_RETURNED, 'PRODUCT RETURNED'),
    (SOLD_PRODUCT_DELIVERED, 'PRODUCT DELIVERED'),
)

VENDOR_PAYMENT_DAY = settings.VENDOR_PAYMENT_DAY